package com.sqldalmaker.thesaurus.dto;

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

public class RelatedWord  {

    private Object rgPartOfSpeech;  // q(RG_PART_OF_SPEECH)
    private Object rgOrder;  // q(RG_ORDER)
    private Object rgwId;  // q(RGW_ID)
    private Object rgId;  // q(RG_ID)
    private Object rgwWord;  // q(RGW_WORD)
    private Object rgwNote;  // q(RGW_NOTE)
    private Object rgwOrder;  // q(RGW_ORDER)

    public Object getRgPartOfSpeech() {
        return this.rgPartOfSpeech;
    }

    public void setRgPartOfSpeech(Object rgPartOfSpeech) {
        this.rgPartOfSpeech = rgPartOfSpeech;
    }

    public Object getRgOrder() {
        return this.rgOrder;
    }

    public void setRgOrder(Object rgOrder) {
        this.rgOrder = rgOrder;
    }

    public Object getRgwId() {
        return this.rgwId;
    }

    public void setRgwId(Object rgwId) {
        this.rgwId = rgwId;
    }

    public Object getRgId() {
        return this.rgId;
    }

    public void setRgId(Object rgId) {
        this.rgId = rgId;
    }

    public Object getRgwWord() {
        return this.rgwWord;
    }

    public void setRgwWord(Object rgwWord) {
        this.rgwWord = rgwWord;
    }

    public Object getRgwNote() {
        return this.rgwNote;
    }

    public void setRgwNote(Object rgwNote) {
        this.rgwNote = rgwNote;
    }

    public Object getRgwOrder() {
        return this.rgwOrder;
    }

    public void setRgwOrder(Object rgwOrder) {
        this.rgwOrder = rgwOrder;
    }
}