package com.sqldalmaker.thesaurus.dto;

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

public class Word  {

    private Integer wId;  // t(W_ID)
    private String wWord;  // t(W_WORD)

    public Integer getWId() {
        return this.wId;
    }

    public void setWId(Integer wId) {
        this.wId = wId;
    }

    public String getWWord() {
        return this.wWord;
    }

    public void setWWord(String wWord) {
        this.wWord = wWord;
    }
}